version: '3.8'

services:
  porteiro-api:
    build: .
    container_name: porteiro-api
    mem_limit: 512m
    env_file:
      - .env
    ports:
      - '8082:8082'
    depends_on: []
    restart: always
