-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    email character varying(50) COLLATE pg_catalog."default",
    password character varying(120) COLLATE pg_catalog."default",
    username character varying(20) COLLATE pg_catalog."default",
    access_token character varying(255) COLLATE pg_catalog."default",
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    update_at timestamp(6) without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

END;